version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
      - ppc64le
      - s390x
      - riscv64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: ppc64le
      - goos: darwin
        goarch: s390x
      - goos: darwin
        goarch: riscv64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: ppc64le
      - goos: windows
        goarch: s390x
      - goos: windows
        goarch: riscv64
    ldflags:
      - -s -w
      - -X '{{ .ModulePath }}/cmd.version={{ .Version }}'
      - -X '{{ .ModulePath }}/cmd.commit={{ .Commit }}'
      - -X '{{ .ModulePath }}/cmd.date={{ .Date }}'

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}

dockers_v2:
  - images:
      - "circa10a/dead-mans-switch"
    tags:
      - "{{ .Tag }}"
      - latest
    dockerfile: Dockerfile.goreleaser
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v7
      - linux/arm/v6
      - linux/386
      - linux/ppc64le
      - linux/s390x
      - linux/riscv64

changelog:
  disable: false
  sort: asc
