{
 "title": "Dead Man's Switch",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "DS_LOKI", "label": "datasource", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[$__range])) by (handler)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request duration by handler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(1,sum(rate(http_request_duration_seconds_bucket[$__range])) by (handler, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{status=~\"5.*\"}[$__range])) / sum(rate(http_request_duration_seconds_count[$__range])) * 100 > 5",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dead Man's Switch non HTTP logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container=\"dead-mans-switch\"} != `method`"
    }
   ]
  },
  {
   "title": "Dead Man's Switch HTTP error logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 8 },
   "targets": [
    {
     "expr": "{container=\"dead-mans-switch\"} | json | status != `200` | component != `server`"
    }
   ]
  }
 ]
}