// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for HealthStatus.
const (
	Failed HealthStatus = "failed"
	Ok     HealthStatus = "ok"
)

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// PushSubscription defines model for PushSubscription.
type PushSubscription struct {
	Endpoint *string `json:"endpoint,omitempty"`
	Keys     *struct {
		Auth   *string `json:"auth,omitempty"`
		P256dh *string `json:"p256dh,omitempty"`
	} `json:"keys,omitempty"`
}

// Switch defines model for Switch.
type Switch struct {
	CheckInInterval  string            `json:"checkInInterval" validate:"required"`
	DeleteAfterSent  bool              `json:"deleteAfterSent"`
	Disabled         bool              `json:"disabled"`
	Encrypted        bool              `json:"encrypted"`
	Id               *int              `json:"id,omitempty"`
	Message          string            `json:"message" validate:"required,min=1"`
	Notifiers        []string          `json:"notifiers" validate:"required,min=1"`
	PushSubscription *PushSubscription `json:"pushSubscription,omitempty"`
	ReminderSent     *bool             `json:"reminderSent,omitempty"`

	// ReminderThreshold How long before expiration to send a PWA reminder
	ReminderThreshold *string `json:"reminderThreshold,omitempty"`

	// SendAt Time to send in Unix time format
	SendAt *int64 `json:"sendAt,omitempty"`
	Sent   *bool  `json:"sent,omitempty"`
}

// GetSwitchParams defines parameters for GetSwitch.
type GetSwitchParams struct {
	// Limit Limit the number of switches returned (default is 100)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostSwitchJSONRequestBody defines body for PostSwitch for application/json ContentType.
type PostSwitchJSONRequestBody = Switch

// PutSwitchIdJSONRequestBody defines body for PutSwitchId for application/json ContentType.
type PutSwitchIdJSONRequestBody = Switch

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSwitch request
	GetSwitch(ctx context.Context, params *GetSwitchParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostSwitchWithBody request with any body
	PostSwitchWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostSwitch(ctx context.Context, body PostSwitchJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteSwitchId request
	DeleteSwitchId(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSwitchId request
	GetSwitchId(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutSwitchIdWithBody request with any body
	PutSwitchIdWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutSwitchId(ctx context.Context, id int, body PutSwitchIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostSwitchIdDisable request
	PostSwitchIdDisable(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostSwitchIdReset request
	PostSwitchIdReset(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetVapid request
	GetVapid(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSwitch(ctx context.Context, params *GetSwitchParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSwitchRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSwitchWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSwitchRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSwitch(ctx context.Context, body PostSwitchJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSwitchRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteSwitchId(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteSwitchIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSwitchId(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSwitchIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutSwitchIdWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutSwitchIdRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutSwitchId(ctx context.Context, id int, body PutSwitchIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutSwitchIdRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSwitchIdDisable(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSwitchIdDisableRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostSwitchIdReset(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostSwitchIdResetRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetVapid(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetVapidRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSwitchRequest generates requests for GetSwitch
func NewGetSwitchRequest(server string, params *GetSwitchParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/switch")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostSwitchRequest calls the generic PostSwitch builder with application/json body
func NewPostSwitchRequest(server string, body PostSwitchJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostSwitchRequestWithBody(server, "application/json", bodyReader)
}

// NewPostSwitchRequestWithBody generates requests for PostSwitch with any type of body
func NewPostSwitchRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/switch")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteSwitchIdRequest generates requests for DeleteSwitchId
func NewDeleteSwitchIdRequest(server string, id int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/switch/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSwitchIdRequest generates requests for GetSwitchId
func NewGetSwitchIdRequest(server string, id int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/switch/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutSwitchIdRequest calls the generic PutSwitchId builder with application/json body
func NewPutSwitchIdRequest(server string, id int, body PutSwitchIdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutSwitchIdRequestWithBody(server, id, "application/json", bodyReader)
}

// NewPutSwitchIdRequestWithBody generates requests for PutSwitchId with any type of body
func NewPutSwitchIdRequestWithBody(server string, id int, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/switch/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostSwitchIdDisableRequest generates requests for PostSwitchIdDisable
func NewPostSwitchIdDisableRequest(server string, id int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/switch/%s/disable", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostSwitchIdResetRequest generates requests for PostSwitchIdReset
func NewPostSwitchIdResetRequest(server string, id int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/switch/%s/reset", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetVapidRequest generates requests for GetVapid
func NewGetVapidRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/vapid")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)

	// GetSwitchWithResponse request
	GetSwitchWithResponse(ctx context.Context, params *GetSwitchParams, reqEditors ...RequestEditorFn) (*GetSwitchResponse, error)

	// PostSwitchWithBodyWithResponse request with any body
	PostSwitchWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSwitchResponse, error)

	PostSwitchWithResponse(ctx context.Context, body PostSwitchJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSwitchResponse, error)

	// DeleteSwitchIdWithResponse request
	DeleteSwitchIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*DeleteSwitchIdResponse, error)

	// GetSwitchIdWithResponse request
	GetSwitchIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*GetSwitchIdResponse, error)

	// PutSwitchIdWithBodyWithResponse request with any body
	PutSwitchIdWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutSwitchIdResponse, error)

	PutSwitchIdWithResponse(ctx context.Context, id int, body PutSwitchIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PutSwitchIdResponse, error)

	// PostSwitchIdDisableWithResponse request
	PostSwitchIdDisableWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*PostSwitchIdDisableResponse, error)

	// PostSwitchIdResetWithResponse request
	PostSwitchIdResetWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*PostSwitchIdResetResponse, error)

	// GetVapidWithResponse request
	GetVapidWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetVapidResponse, error)
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Health
	JSON503      *Health
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetSwitchResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Switch
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GetSwitchResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSwitchResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostSwitchResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Switch
	JSON400      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r PostSwitchResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostSwitchResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteSwitchIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Switch
	JSON404      *Error
}

// Status returns HTTPResponse.Status
func (r DeleteSwitchIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteSwitchIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetSwitchIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Switch
	JSON404      *Error
}

// Status returns HTTPResponse.Status
func (r GetSwitchIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSwitchIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutSwitchIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Switch
	JSON400      *Error
	JSON404      *Error
}

// Status returns HTTPResponse.Status
func (r PutSwitchIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutSwitchIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostSwitchIdDisableResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Switch
	JSON404      *Error
}

// Status returns HTTPResponse.Status
func (r PostSwitchIdDisableResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostSwitchIdDisableResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostSwitchIdResetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Switch
	JSON404      *Error
}

// Status returns HTTPResponse.Status
func (r PostSwitchIdResetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostSwitchIdResetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetVapidResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetVapidResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetVapidResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// GetSwitchWithResponse request returning *GetSwitchResponse
func (c *ClientWithResponses) GetSwitchWithResponse(ctx context.Context, params *GetSwitchParams, reqEditors ...RequestEditorFn) (*GetSwitchResponse, error) {
	rsp, err := c.GetSwitch(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSwitchResponse(rsp)
}

// PostSwitchWithBodyWithResponse request with arbitrary body returning *PostSwitchResponse
func (c *ClientWithResponses) PostSwitchWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostSwitchResponse, error) {
	rsp, err := c.PostSwitchWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSwitchResponse(rsp)
}

func (c *ClientWithResponses) PostSwitchWithResponse(ctx context.Context, body PostSwitchJSONRequestBody, reqEditors ...RequestEditorFn) (*PostSwitchResponse, error) {
	rsp, err := c.PostSwitch(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSwitchResponse(rsp)
}

// DeleteSwitchIdWithResponse request returning *DeleteSwitchIdResponse
func (c *ClientWithResponses) DeleteSwitchIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*DeleteSwitchIdResponse, error) {
	rsp, err := c.DeleteSwitchId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteSwitchIdResponse(rsp)
}

// GetSwitchIdWithResponse request returning *GetSwitchIdResponse
func (c *ClientWithResponses) GetSwitchIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*GetSwitchIdResponse, error) {
	rsp, err := c.GetSwitchId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSwitchIdResponse(rsp)
}

// PutSwitchIdWithBodyWithResponse request with arbitrary body returning *PutSwitchIdResponse
func (c *ClientWithResponses) PutSwitchIdWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutSwitchIdResponse, error) {
	rsp, err := c.PutSwitchIdWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutSwitchIdResponse(rsp)
}

func (c *ClientWithResponses) PutSwitchIdWithResponse(ctx context.Context, id int, body PutSwitchIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PutSwitchIdResponse, error) {
	rsp, err := c.PutSwitchId(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutSwitchIdResponse(rsp)
}

// PostSwitchIdDisableWithResponse request returning *PostSwitchIdDisableResponse
func (c *ClientWithResponses) PostSwitchIdDisableWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*PostSwitchIdDisableResponse, error) {
	rsp, err := c.PostSwitchIdDisable(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSwitchIdDisableResponse(rsp)
}

// PostSwitchIdResetWithResponse request returning *PostSwitchIdResetResponse
func (c *ClientWithResponses) PostSwitchIdResetWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*PostSwitchIdResetResponse, error) {
	rsp, err := c.PostSwitchIdReset(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostSwitchIdResetResponse(rsp)
}

// GetVapidWithResponse request returning *GetVapidResponse
func (c *ClientWithResponses) GetVapidWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetVapidResponse, error) {
	rsp, err := c.GetVapid(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetVapidResponse(rsp)
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Health
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Health
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseGetSwitchResponse parses an HTTP response from a GetSwitchWithResponse call
func ParseGetSwitchResponse(rsp *http.Response) (*GetSwitchResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSwitchResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Switch
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostSwitchResponse parses an HTTP response from a PostSwitchWithResponse call
func ParsePostSwitchResponse(rsp *http.Response) (*PostSwitchResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostSwitchResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Switch
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteSwitchIdResponse parses an HTTP response from a DeleteSwitchIdWithResponse call
func ParseDeleteSwitchIdResponse(rsp *http.Response) (*DeleteSwitchIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteSwitchIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Switch
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetSwitchIdResponse parses an HTTP response from a GetSwitchIdWithResponse call
func ParseGetSwitchIdResponse(rsp *http.Response) (*GetSwitchIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSwitchIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Switch
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParsePutSwitchIdResponse parses an HTTP response from a PutSwitchIdWithResponse call
func ParsePutSwitchIdResponse(rsp *http.Response) (*PutSwitchIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutSwitchIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Switch
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParsePostSwitchIdDisableResponse parses an HTTP response from a PostSwitchIdDisableWithResponse call
func ParsePostSwitchIdDisableResponse(rsp *http.Response) (*PostSwitchIdDisableResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostSwitchIdDisableResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Switch
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParsePostSwitchIdResetResponse parses an HTTP response from a PostSwitchIdResetWithResponse call
func ParsePostSwitchIdResetResponse(rsp *http.Response) (*PostSwitchIdResetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostSwitchIdResetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Switch
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetVapidResponse parses an HTTP response from a GetVapidWithResponse call
func ParseGetVapidResponse(rsp *http.Response) (*GetVapidResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetVapidResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
